### ISSUE TITLE
App crashes when setting/saving images

### ISSUE THREAD

**Issue by OraBB1t** [enricocid/VectorifyDaHome#32]
**Issue** -
After 0.9.2 update, when I try to set/save an image the app crashes.
0.9.1 works perfectly.

**To reproduce** -
Try setting/saving any image.

**Expected behavior** -
Set/save the image.

**My input** -
I think this is due to Android 10's scoped storage.
After 0.9.2 update, app uses /Pictures folder. To access this folder you need 'Storage' permission.
But the app never asks for this permission(tried reinstalling in case I missed it).
So when tried to set/save an image since it can't access the folder, it crashes.
That's my theory.

 - Device: OnePlus5
 - OS: Android 10
 - ROM : LineageOS 17.1

**Comment by enricocid** [comment]
Hi,

could you try the latest [build](https://github.com/enricocid/VectorifyDaHome/actions/runs/1120149200) and confirm this is now fixed?
Thanks :)

**Comment by OraBB1t** [comment]
Hey,
I tried the build. Now the app doesn't crash but shows 'Boo No access no party!...' toast.
Still doesn't set/save images.
This build doesn't ask for storage permission either. Can't grant storage permission if the app doesn't request it.
@enricocid

**Comment by OraBB1t** [comment]
I'm not a developer but I think you should add,
`android:requestLegacyExternalStorage="true"`
to app's manifest file.

**Comment by enricocid** [comment]
Share a logcat 😉

Anyway it's weird, I'm on lineage 17.1 (03/08 build) and it is working now. 😬
Try the PlayStore build.

Since Android 10 storage permission is not needed to save files on shared storage (media and downloads).

**Comment by OraBB1t** [comment]
1.9.4 build has fixed the issue! Works as expected now.

**Comment by enricocid** [comment]
Thanks 😁🙏🏻
